/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/argoproj/argo-rollouts/pkg/apis/rollouts/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeISDTemplates implements ISDTemplateInterface
type FakeISDTemplates struct {
	Fake *FakeArgoprojV1alpha1
	ns   string
}

var isdtemplatesResource = schema.GroupVersionResource{Group: "argoproj.io", Version: "v1alpha1", Resource: "isdtemplates"}

var isdtemplatesKind = schema.GroupVersionKind{Group: "argoproj.io", Version: "v1alpha1", Kind: "ISDTemplate"}

// Get takes name of the iSDTemplate, and returns the corresponding iSDTemplate object, and an error if there is any.
func (c *FakeISDTemplates) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ISDTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(isdtemplatesResource, c.ns, name), &v1alpha1.ISDTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ISDTemplate), err
}

// List takes label and field selectors, and returns the list of ISDTemplates that match those selectors.
func (c *FakeISDTemplates) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ISDTemplateList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(isdtemplatesResource, isdtemplatesKind, c.ns, opts), &v1alpha1.ISDTemplateList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ISDTemplateList{ListMeta: obj.(*v1alpha1.ISDTemplateList).ListMeta}
	for _, item := range obj.(*v1alpha1.ISDTemplateList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested iSDTemplates.
func (c *FakeISDTemplates) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(isdtemplatesResource, c.ns, opts))

}

// Create takes the representation of a iSDTemplate and creates it.  Returns the server's representation of the iSDTemplate, and an error, if there is any.
func (c *FakeISDTemplates) Create(ctx context.Context, iSDTemplate *v1alpha1.ISDTemplate, opts v1.CreateOptions) (result *v1alpha1.ISDTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(isdtemplatesResource, c.ns, iSDTemplate), &v1alpha1.ISDTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ISDTemplate), err
}

// Update takes the representation of a iSDTemplate and updates it. Returns the server's representation of the iSDTemplate, and an error, if there is any.
func (c *FakeISDTemplates) Update(ctx context.Context, iSDTemplate *v1alpha1.ISDTemplate, opts v1.UpdateOptions) (result *v1alpha1.ISDTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(isdtemplatesResource, c.ns, iSDTemplate), &v1alpha1.ISDTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ISDTemplate), err
}

// Delete takes name of the iSDTemplate and deletes it. Returns an error if one occurs.
func (c *FakeISDTemplates) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(isdtemplatesResource, c.ns, name, opts), &v1alpha1.ISDTemplate{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeISDTemplates) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(isdtemplatesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ISDTemplateList{})
	return err
}

// Patch applies the patch and returns the patched iSDTemplate.
func (c *FakeISDTemplates) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ISDTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(isdtemplatesResource, c.ns, name, pt, data, subresources...), &v1alpha1.ISDTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ISDTemplate), err
}
